version: '3'

services:
  mongodb:
    image: mongo:4-bionic
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-net
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    command: [--auth]
    restart: always

  nosqlclient:
    image: mongoclient/mongoclient:4.0.1
    container_name: nosqlclient
    volumes:
      - nosqldata:/data/db
    ports:
      - 27018:3000
    networks:
      - mongo-net



networks:
  mongo-net:
    driver: bridge

volumes:
  dbdata:
  nosqldata:
